(defpackage #:mtm
  (:use #:cl)
  (:import-from #:mtm.frontend
                #:set-passthrough-frontend)
  (:import-from #:mtm.client
                #:del-attachment
                #:del-service
                #:del-session
                #:del-session-manager
                #:get-service
                #:get-service-list
                #:get-service-output
                #:get-session
                #:get-session-list
                #:get-session-manager
                #:new-service-source
                #:new-session
                #:new-session-manager
                #:set-service)
  (:import-from #:mtm.session
                #:attachment
                #:attachment-session
                #:attachment-attached-p
                #:get-session-size
                #:get-attachment-output
                #:get-attachment-start-screen
                #:get-retained-screen
                #:new-attachment
                #:new-service
                #:session-name
                #:session-running-p
                #:set-attachment-input
                #:set-attachment-terminal-size)
  (:export
   #:attachment
   #:attachment-session
   #:attachment-attached-p
   #:del-attachment
   #:del-service
   #:del-session
   #:del-session-manager
   #:get-attachment-output
   #:get-attachment-start-screen
   #:get-retained-screen
   #:get-session
   #:get-session-list
   #:get-session-size
   #:get-session-manager
   #:get-service
   #:get-service-list
   #:get-service-output
   #:new-attachment
   #:new-service
   #:new-service-source
   #:new-session
   #:new-session-manager
   #:session-name
   #:session-running-p
   #:set-service
   #:set-attachment-input
   #:set-attachment-terminal-size
   #:set-passthrough-frontend))
